-- ============================================================
-- MENU_MASTER seed data
-- Mirrors the hardcoded sidebarMenu.js hierarchy exactly.
-- Run once; safe to re-run only if table is empty.
-- ============================================================

-- ── Level 1 : Parent sections ────────────────────────────────
INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M001', 'MENU', 'USER',     'User',              NULL, NULL, 1, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M002', 'MENU', 'MASTER',   'Master',            NULL, NULL, 2, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M003', 'MENU', 'PATIENT',  'Patient',           NULL, NULL, 3, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M004', 'MENU', 'CLINICAL', 'Clinical Services', NULL, NULL, 4, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M005', 'MENU', 'DOCTOR',   'Doctor',            NULL, NULL, 5, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M006', 'MENU', 'BILLING',  'Billing',           NULL, NULL, 6, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M007', 'MENU', 'REPORTS',  'Reports',           NULL, NULL, 7, 'ACTIVE');

-- ── Level 2 : User ───────────────────────────────────────────
INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M101', 'MENU', 'USER_NEW',  'New User',  '/new-user',  'M001', 1, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M102', 'MENU', 'USER_LIST', 'User List', '/user-list', 'M001', 2, 'ACTIVE');

-- ── Level 2 : Master ─────────────────────────────────────────
INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M201', 'MENU', 'MASTER_LOCATION', 'Location Master',       '/location-master',       'M002', 1, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M202', 'MENU', 'MASTER_LAB_TEST', 'Lab Test Master',       '/lab-test-master',       'M002', 2, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M203', 'MENU', 'MASTER_PHARMACY', 'Pharmacy Item Master',  '/pharmacy-item-master',  'M002', 3, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M204', 'MENU', 'MASTER_FACILITY', 'Facility Master',       '/facility-master',       'M002', 4, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M205', 'MENU', 'MASTER_DOCTOR',   'Doctor Master',         '/doctor-master',         'M002', 5, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M206', 'MENU', 'MASTER_IMPORT',   'Import Data',           '/import-file',           'M002', 6, 'ACTIVE');

-- ── Level 2 : Patient ────────────────────────────────────────
INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M301', 'MENU', 'PATIENT_NEW',          'New Patient',          '/patient',      'M003', 1, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M302', 'MENU', 'PATIENT_REGISTRATION', 'Patient Registration', '/registration', 'M003', 2, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M303', 'MENU', 'PATIENT_ADMISSION',    'Patient Admission',    '/admission',    'M003', 3, 'ACTIVE');

-- ── Level 2 : Clinical Services ──────────────────────────────
INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M401', 'MENU', 'CLINICAL_TEST',         'Test',            '/test',         'M004', 1, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M402', 'MENU', 'CLINICAL_TEST_RESULTS', 'Test Results',    '/result',       'M004', 2, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M403', 'MENU', 'CLINICAL_PHARMACY',     'Pharmacy Items',  '/medical-item', 'M004', 3, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M404', 'MENU', 'CLINICAL_SERVICE',      'Service',         '/service',      'M004', 4, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M405', 'MENU', 'CLINICAL_APPOINTMENT',  'Appointment',     '/appointment',  'M004', 5, 'ACTIVE');

-- ── Level 2 : Doctor ─────────────────────────────────────────
INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M501', 'MENU', 'DOCTOR_NEW',          'New Doctor',           '/new-doctor',   'M005', 1, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M502', 'MENU', 'DOCTOR_CONSULTATION', 'Doctor Consultations', '/consultation', 'M005', 2, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M503', 'MENU', 'DOCTOR_PRESCRIPTION', 'Prescriptions',        '/prescription', 'M005', 3, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M504', 'MENU', 'DOCTOR_APPOINTMENT',  'Appointments',         '/appointment',  'M005', 4, 'ACTIVE');

-- ── Level 2 : Billing ────────────────────────────────────────
INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M601', 'MENU', 'BILLING_VIEW_BILLS', 'View Bills',      '/view-bills', 'M006', 1, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M602', 'MENU', 'BILLING_PAYMENT',    'Record Payment',  '/payment',    'M006', 2, 'ACTIVE');

-- ── Level 2 : Reports ────────────────────────────────────────
INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M701', 'MENU', 'REPORTS_TABULAR', 'Tabular', NULL,    'M007', 1, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M702', 'MENU', 'REPORTS_CHARTS',  'Charts',  '/chart', 'M007', 2, 'ACTIVE');

-- ── Level 3 : Reports > Tabular ──────────────────────────────
INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M711', 'MENU', 'REPORTS_TAB_STATEWISE',   'Patient Statewise',       '/patient-state-wise', 'M701', 1, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M712', 'MENU', 'REPORTS_TAB_DOCTOR_COL',  'Doctor Collection',        '/doctor-wise-reg',    'M701', 2, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M713', 'MENU', 'REPORTS_TAB_LAB',         'Lab Performance',          '/dept-test-doc',      'M701', 3, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M714', 'MENU', 'REPORTS_TAB_REFERRAL',    'Referral Doctor Summary',  '/referral-doc',       'M701', 4, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M715', 'MENU', 'REPORTS_TAB_DOC_TEST',    'Doctor Test Collection',   '/dept-doc',           'M701', 5, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M716', 'MENU', 'REPORTS_TAB_AUDIT',       'Audit Log',                '/audit-master',       'M701', 6, 'ACTIVE');

INSERT INTO MENU_MASTER (MENU_ID, MENU_TYPE, MENU_CODE, MENU_NAME, MENU_URL, PARENT_MENU_ID, DISPLAY_ORDER, STATUS)
VALUES ('M717', 'MENU', 'REPORTS_TAB_DAILY',       'Daily Collection',         '/daily-earnings',     'M701', 7, 'ACTIVE');

COMMIT;
